<?php


namespace app\controllers;

use app\models\CheckingOnlineUser;
use app\models\User;
use yii\web\Controller;
use Yii;

class AppController extends Controller
{

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (!Yii::$app->user->isGuest) $this->setOnlineTime();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function setOnlineTime()
    {
        $user = User::findOne(Yii::$app->user->id);
        if ($checkingOnline = $user->checkingOnline) {
            $checkingOnline->setLastActiveTime();
            return true;
        } else {
            $checkingOnline = new CheckingOnlineUser();
            $checkingOnline->addCheckingOnline(Yii::$app->user->id);
            return true;
        }
    }
}