<?php


namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;

class BehaviorsUserPartController extends AppController
{

    public function beforeAction($action)
    {
        // Подключение шаблона администратора в пользовательской части
        if (User::isUserDev(Yii::$app->user->identity['username']) || User::isUserMainAdmin(Yii::$app->user->identity['username'])
            || User::isUserAdmin(Yii::$app->user->identity['username'])){
            $this->layout = '@app/modules/admin/views/layouts/main-user';
        }

        // Подключение шаблона эксперта в пользовательской части
        if (User::isUserExpert(Yii::$app->user->identity['username'])){
            $this->layout = '@app/modules/expert/views/layouts/main-user';
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [

                'class' => AccessControl::class,

                /*Вызов исключения в случае отсутствия доступа*/
                /*'denyCallback' => function ($rule, $action) {
                    throw new \Exception('Нет доступа.');
                },*/

                'denyCallback' => function ($rule, $action) {
                    return $this->goHome();
                },

                'rules' => [

                    [
                        'allow' => true,
                        'controllers' => ['site'],
                        'actions' => ['get-form-registration', 'registration', 'singup', 'error', 'login', 'index', 'about', 'send-email', 'reset-password', 'activate-account', 'confidentiality-policy', 'download-presentation'],
                        'verbs' => ['GET', 'POST'],
                        'roles' => ['?']
                    ],

                    [
                        'allow' => true,
                        'controllers' => ['site', 'profile'],
                        'actions' => ['singup', 'login', 'index', 'about', 'send-email', 'reset-password', 'update-profile', 'change-password',
                            'logout', 'project', 'roadmap', 'prefiles', 'not-found'],
                        'verbs' => ['GET', 'POST'],
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return !User::isActiveStatus(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserSimple(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserAdmin(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserMainAdmin(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserDev(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserExpert(Yii::$app->user->identity['username']);
                        }
                    ],
                ]

            ]

        ];
    }
}