<?php


namespace app\modules\expert\controllers;

use app\controllers\AppController;
use app\models\User;
use Yii;
use yii\filters\AccessControl;

class BehaviorsExpertPartController extends AppController
{

    public function beforeAction($action)
    {
        // Подключение шаблона администратора в экспертной части
        if (User::isUserDev(Yii::$app->user->identity['username']) || User::isUserMainAdmin(Yii::$app->user->identity['username'])
            || User::isUserAdmin(Yii::$app->user->identity['username'])){
            $this->layout = '@app/modules/admin/views/layouts/main';
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {
        return [
            'access' => [

                'class' => AccessControl::class,

                /*Вызов исключения в случае отсутствия доступа*/
                'denyCallback' => function ($rule, $action) {
                    return $this->goHome();
                },

                'rules' => [

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserAdmin(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserMainAdmin(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserDev(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserExpert(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'actions' => ['download'],
                        'verbs' => ['GET', 'POST'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserSimple(Yii::$app->user->identity['username']);
                        }
                    ],
                ]

            ]

        ];
    }
}