<?php


namespace app\modules\expert\controllers;

use app\controllers\AppController;
use app\models\ClientSettings;
use app\models\ClientUser;
use app\models\User;
use Yii;
use yii\filters\AccessControl;

class BehaviorsExpertPartController extends AppController
{

    public function beforeAction($action)
    {
        // Подключение шаблона администратора в экспертной части
        if (User::isUserDev(Yii::$app->user->identity['username']) || User::isUserMainAdmin(Yii::$app->user->identity['username'])
            || User::isUserAdmin(Yii::$app->user->identity['username'])){
            $this->layout = '@app/modules/admin/views/layouts/main';
        }

        // Подключение шаблона трекера организации в пользовательской части
        if (User::isUserAdmin(Yii::$app->user->identity['username'])) {
            $user = User::findOne(Yii::$app->user->id);
            /** @var ClientUser $clientUser */
            $clientUser = $user->clientUser;
            $clientSettings = ClientSettings::findOne(['client_id' => $clientUser->getClientId()]);
            $admin = User::findOne($clientSettings->getAdminId());

            if (User::isUserMainAdmin($admin->getUsername())) {
                $this->layout = '@app/modules/admin/views/layouts/main-user';
            } else {
                $this->layout = '@app/modules/client/views/layouts/main-user';
            }
        }

        // Подключение шаблона админа организации в пользовательской части
        if (User::isUserAdminCompany(Yii::$app->user->identity['username'])) {
            $this->layout = '@app/modules/client/views/layouts/main-user';
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {
        return [
            'access' => [

                'class' => AccessControl::class,

                /*Вызов исключения в случае отсутствия доступа*/
                'denyCallback' => function ($rule, $action) {
                    return $this->goHome();
                },

                'rules' => [

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $user = User::findOne(Yii::$app->user->id);
                            /** @var ClientUser $clientUser */
                            $clientUser = $user->clientUser;
                            $isActiveClient = $clientUser->findClient()->isActive();
                            return User::isUserAdmin($user->getUsername()) && $isActiveClient;
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserMainAdmin(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $user = User::findOne(Yii::$app->user->id);
                            /** @var ClientUser $clientUser */
                            $clientUser = $user->clientUser;
                            $isActiveClient = $clientUser->findClient()->isActive();
                            return User::isUserAdminCompany($user->getUsername()) && $isActiveClient;
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserDev(Yii::$app->user->identity['username']);
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $user = User::findOne(Yii::$app->user->id);
                            /** @var ClientUser $clientUser */
                            $clientUser = $user->clientUser;
                            $isActiveClient = $clientUser->findClient()->isActive();
                            return User::isUserExpert($user->getUsername()) && $isActiveClient;
                        }
                    ],

                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'actions' => ['download'],
                        'verbs' => ['GET', 'POST'],
                        'matchCallback' => function ($rule, $action) {
                            $user = User::findOne(Yii::$app->user->id);
                            /** @var ClientUser $clientUser */
                            $clientUser = $user->clientUser;
                            $isActiveClient = $clientUser->findClient()->isActive();
                            return User::isUserSimple($user->getUsername()) && $isActiveClient;
                        }
                    ],
                ]

            ]

        ];
    }
}